# Generated by Django 5.0.6 on 2024-06-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.CharField(max_length=255, verbose_name='описание')),
                ('author', models.CharField(max_length=100, verbose_name='автор')),
                ('published_year', models.DateField(verbose_name='дата публикации')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='созданно')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='обновленно')),
                ('genre', models.CharField(choices=[('FI', 'Художественная литература'), ('NF', 'Документальная литература'), ('FA', 'Фантастика'), ('SF', 'Научная фантастика'), ('MY', 'Детектив'), ('RO', 'Романтика'), ('TH', 'Триллер'), ('HO', 'Ужасы'), ('HI', 'Историческая литература'), ('BI', 'Биография'), ('PO', 'Поэзия'), ('DR', 'Драма'), ('CO', 'Комикс'), ('CL', 'Классическая литература'), ('CH', 'Детская литература'), ('AD', 'Приключения'), ('FB', 'Басня'), ('MYT', 'Мифология'), ('ES', 'Эссе'), ('SCI', 'Научная литература')], max_length=100, verbose_name='жанр')),
            ],
            options={
                'verbose_name': 'Книги',
            },
        ),
    ]
